added 4.1
Frikam/SPBU_HOMEWORK pull request #12
Opened 2018-11-09 10:12 UTC by Frikam

2018-11-20 10:00 UTC, jzuken requested changes

2018-11-20 10:00 UTC, jzuken commented on 4/4.1/4.1/killWarrioirs.hpp
> +void findAndKill(CyclicList *list, int mustDead, int numbOfWarriors, int deadWarriors);
а CyclicList оно откуда возьмёт? у меня оно не компилируется даже

2018-11-20 10:10 UTC, Frikam commented on 4/4.1/4.1/killWarrioirs.hpp
> +void findAndKill(CyclicList *list, int mustDead, int numbOfWarriors, int deadWarriors);
Исправил, у меня компилировало просто.

2018-11-24 18:09 UTC, jzuken requested changes

2018-11-24 18:09 UTC, jzuken commented on 4/4.1/4.1/main.cpp
> +        else{
форматирование

2018-11-24 18:09 UTC, jzuken commented on 4/4.1/4.1/main.cpp
> +    CyclicList *Warriors = createList();
сайлгайд

2018-11-24 18:09 UTC, jzuken commented on 4/4.1/4.1/main.cpp
> +            add(Warriors, i, false);
и что это значит? true и false третьим аргументом, ничего не понятно

2018-11-24 18:09 UTC, jzuken commented on 4/4.1/4.1/CyclicList.cpp
> +void add(CyclicList *list, int x, bool isLast)
а ничего, что isLast тут не используется совсем?

2018-11-24 18:09 UTC, jzuken commented on 4/4.1/4.1/killWarrioirs.cpp
> +    ListElement *current = list->first;
а можно так, чтобы оно не лазило в детали реализации модуля списка?

2018-12-04 11:49 UTC, merged