added task 7.1
Frikam/SPBU_HOMEWORK pull request #13
Opened 2018-11-13 14:11 UTC by Frikam

2018-11-18 16:17 UTC, ujohnny requested changes

2018-11-18 16:17 UTC, ujohnny commented on 7/7.1/7.1/main.cpp
> +#include "BinaryTree.hpp"
у вас стоит задача реализовать Set -- тут везде реализовано только BinaryTree. Смысл в том, чтобы у вас была структура данных сет и ассоциированные с ней методы. использование внутри нее BST это implementation details, оно не должно быть видно снаружи. и в 7.2 вам нужно просто вместо BST подложить внутрь АВЛ дерево

2018-11-18 20:29 UTC, Frikam commented on 7/7.1/7.1/main.cpp
> +#include "BinaryTree.hpp"
Не совсем понимаю что от меня требуется, мне нужно просто переименовать  BinaryTree?

2018-11-18 20:29 UTC, Frikam commented on 7/7.1/7.1/main.cpp
> +#include "BinaryTree.hpp"
Не совсем понимаю что от меня требуется, мне нужно просто переименовать BinaryTree?

2018-11-20 10:26 UTC, jzuken commented on 7/7.1/7.1/main.cpp
> +#include "BinaryTree.hpp"
не, создать новый тип данных

2018-12-04 12:31 UTC, jzuken requested changes

2018-12-04 12:31 UTC, jzuken commented on 7/7.1/7.1/main.cpp
> +int main()
проверь, что вся память очищается при выходе

2018-12-19 11:32 UTC, jzuken requested changes

2018-12-19 11:32 UTC, jzuken commented on 7/7.1/7.1/Set.cpp
> +    delete[] set;
delete[] ?

2018-12-19 11:32 UTC, jzuken commented on 7/7.1/7.1/Tree.cpp
> +void deleteTree(Tree *tree)
ещё раз: проверь, что всё удаляется, что нужно

2018-12-21 14:37 UTC, jzuken commented
не всё удалил

2018-12-21 14:38 UTC, jzuken commented
(5 (4 (3 null null)null)(7 (6 null null)(8 null null)))
Enter number of function : 3
Enter value : 5
Enter number of function : 7
(6 (4 (3 null null)null)null)

2018-12-23 14:04 UTC, jzuken commented
запустил программу, закрыл сразу: 

==3710== 8 bytes in 1 blocks are definitely lost

что-то я не вижу смысла уже ничего проверять, лучше то не становится, одни и те же ошибки в каждой задаче

2018-12-23 14:10 UTC, Frikam commented
@jzuken можете подсказать где я могу терять память? Я просто сейчас не могу понять где я ее теряю. При удалении элемента память вроде  очищаю, при удаление set'a тоже. Буду очень признателен

2018-12-23 14:25 UTC, Frikam commented
@jzuken Вроде нашел утечку, у меня если дерево пустое, оно не удаляло само дерево.

2018-12-24 09:03 UTC, merged