added task 8.2
Frikam/SPBU_HOMEWORK pull request #18
Opened 2018-11-22 13:56 UTC by Frikam

2018-12-03 14:11 UTC, jzuken requested changes

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/main.cpp
> +int main()
HEAP SUMMARY:
  in use at exit: 73,737 bytes in 5 blocks
total heap usage: 16 allocs, 11 frees, 84,013 bytes allocated

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +    newString->word = new char [newString->length];
тут пробел лишний

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +bool isEqual(String *firstWord, String *secondWord)
areEqual тогда уж

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +
лишняя пустая строка

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +    if (string->length == 0)
печаль

2018-12-03 14:11 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +void concatenation(String *firstWord, String *secondWord)
имя функции -- глагол

2018-12-03 14:36 UTC, Frikam commented on 8/8.2/8.2/string.cpp
> +
Можно их оставлять? Для меня так намного легче отделять блоки

2018-12-03 15:13 UTC, Frikam commented on 8/8.2/8.2/string.cpp
> +    newString->word = new char [newString->length];
После char?

2018-12-03 16:34 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +
одной вполне достаточно

2018-12-03 16:34 UTC, jzuken commented on 8/8.2/8.2/string.cpp
> +    newString->word = new char [newString->length];
да

2018-12-16 13:28 UTC, jzuken requested changes

2018-12-16 13:28 UTC, jzuken commented on 8/8.2/8.2/main.cpp
> +    char *newWord = new char[maxLength];
пыщь

2018-12-16 13:33 UTC, Frikam commented on 8/8.2/8.2/main.cpp
> +    char *newWord = new char[maxLength];
@jzuken Так вы же мне выше писали, что пробел после char не нужен, или я не на то внимание обращаю?

2018-12-17 04:13 UTC, jzuken commented on 8/8.2/8.2/main.cpp
> +    char *newWord = new char[maxLength];
я про память

2018-12-21 11:05 UTC, merged