added task 8.3
Frikam/SPBU_HOMEWORK pull request #23
Opened 2018-11-30 01:37 UTC by Frikam

2018-12-06 10:25 UTC, jzuken commented
с памятью всё плохо тут очень

2018-12-06 10:31 UTC, jzuken commented on 8/8.3/8.3/hash.cpp
> +        index = (index + step) % hashTable->maxLength;
и это квадратичная последовательность проб?

2018-12-06 10:31 UTC, jzuken commented on 8/8.3/8.3/hash.cpp
> +int getMaxNumberOfSamples (HashTable *hashTable)
пробел лишний

2018-12-06 10:31 UTC, jzuken commented on 8/8.3/8.3/hash.hpp
> +
хочется ещё функцию проверки, есть ли там заданное слово

2018-12-06 10:31 UTC, jzuken commented on 8/8.3/8.3/main.cpp
> +    return !(sign == ' ' || sign == '?' || sign == '!' || sign == ','
неудачный подход, я вроде бы уже писал об этом

2018-12-06 12:38 UTC, Frikam commented on 8/8.3/8.3/hash.hpp
> +
А какое слово будет использоваться?
У нас же на вход подается файл

2018-12-06 12:43 UTC, Frikam commented on 8/8.3/8.3/hash.hpp
> +
@jzuken Я правильно понял, что проверяем слово, которое мы собираемся добавлять?

2018-12-07 12:51 UTC, jzuken commented on 8/8.3/8.3/hash.hpp
> +
ну просто функция типа как была exists() в списках и прочих деревьях

2018-12-18 07:19 UTC, jzuken commented
всё ещё много лишних строк создаётся. и один неправильный delete

2018-12-18 07:20 UTC, jzuken requested changes

2018-12-18 07:20 UTC, jzuken commented on 8/8.3/8.3/hash.cpp
> +    for (int i = 0; i < hashTable->maxLength; i++)
эээ, ну нет, это не так делается

2018-12-21 12:11 UTC, jzuken commented
с памятью всё ещё плохо

2018-12-23 14:05 UTC, jzuken commented
и тут та же история

==3788== 2 bytes in 1 blocks are indirectly lost 

==3788== 18 (16 direct, 2 indirect) bytes in 1 blocks are definitely lost

2018-12-24 09:04 UTC, merged