added task 9.2
Frikam/SPBU_HOMEWORK pull request #26
Opened 2018-12-09 14:58 UTC by Frikam

2018-12-18 07:49 UTC, ujohnny requested changes

2018-12-18 07:49 UTC, ujohnny commented on 9/9.2/9.2/main.cpp
> +        if (!input.eof())
зачем условие то повторяется?

2018-12-18 07:49 UTC, ujohnny commented on 9/9.2/9.2/main.cpp
> +    encode(tree);
почему построение дерева назывется encode? encode это когда дали нормальную строчку, а получили закодированную

2018-12-18 13:59 UTC, ujohnny commented on 9/9.2/9.2/main.cpp
> +            addSign(tree, sign);
sign --  это скорее + или -. а тут char/character

2018-12-18 13:59 UTC, ujohnny commented on 9/9.2/9.2/HuffmanCode.cpp
> +            tree->size = 0;
это что такое?

2018-12-18 13:59 UTC, ujohnny commented on 9/9.2/9.2/HuffmanCode.cpp
> +    while (tree->tree[index] && tree->tree[index]->sign != sign)
а если  tree nullptr?

2018-12-18 13:59 UTC, ujohnny commented on 9/9.2/9.2/main.cpp
> +        for (int j = 0; j < tree->size; j++)
вы считаете эту реализацию эффективной?

2018-12-18 16:06 UTC, Frikam commented on 9/9.2/9.2/HuffmanCode.cpp
> +    while (tree->tree[index] && tree->tree[index]->sign != sign)
@ujohnny оно не может быть nullptr, тк я его создал до этого

2018-12-18 16:06 UTC, Frikam commented on 9/9.2/9.2/main.cpp
> +        for (int j = 0; j < tree->size; j++)
В целом ее сложность не очень большая

2018-12-18 16:15 UTC, jzuken commented
сделал вот такой файл и всё упало:

```
beep boop beer!

test...
asd
```

2018-12-18 16:20 UTC, jzuken requested changes

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/HuffmanCode.cpp
> +    while (tree->tree[index] && tree->tree[index]->sign != sign)
ну вообще эта функция публичная для данного модуля, так что её может вызвать кто угодно когда угодно

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/HuffmanCode.cpp
> +        tree->tree[index]->parent = nullptr;
а нельзя ему это просто списком полей передать при создании?

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/HuffmanCode.cpp
> +    HuffmanNode *mainNode;
почему бы сразу не проинициализировать?

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/HuffmanCode.hpp
> +void addSign(HuffmanTree *tree, char sign);
точно эти все функции должны быть частью публичного интерфейса модуля?

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/main.cpp
> +        if (!input.eof())
так зачем оно повторяется?

2018-12-18 16:20 UTC, jzuken commented on 9/9.2/9.2/main.cpp
> +        for (int j = 0; j < tree->size; j++)
не очень большая это сколько?

2018-12-18 19:56 UTC, Frikam commented on 9/9.2/9.2/main.cpp
> +        for (int j = 0; j < tree->size; j++)
@jzuken Не такая большая, как я мог сделать) Просто я так сказал, тк пытался оптимизоровать алгоритм на поиске минимального элемента(меньше чем О(n)).
На данный момент не особо вижу части кода, которые можно сильно оптимизировать.

2018-12-18 20:14 UTC, Frikam commented
@jzuken Повторяется тк в какой-то из задач у меня при таком считывании последний элемент считывался дважды, поэтому я делаю так

2018-12-23 14:09 UTC, jzuken commented
8 bytes in 1 blocks are definitely lost

2018-12-23 14:13 UTC, jzuken requested changes

2018-12-23 14:13 UTC, jzuken commented on 9/9.2/9.2/main.cpp
> +    buildTree(tree);
всю эту логику надо убрать внутрь модуля работы с алгоритмом хаффмана. main должен вызывать высокоуровневые функции, тут не интересны детали реализации. опять же весь семестр про это твержу

2018-12-23 15:08 UTC, Frikam commented on 9/9.2/9.2/HuffmanCode.hpp
> +void addSign(HuffmanTree *tree, char sign);
Да, все нужны.

2018-12-24 09:09 UTC, jzuken commented
просил же писать в выходной файл только то, что надо в 9.3

2018-12-24 09:10 UTC, Frikam commented
@jzuken я сделал так, что бы у нас в 9.3 считывался файл из 9.2

2018-12-24 09:11 UTC, Frikam commented
@jzuken я возможно вас неправильно понял, но сделал я именно так. Просто в заданит от нас требуется именно это

2018-12-24 09:11 UTC, jzuken commented
а, значит я зря файл сидел правил)

2018-12-24 09:13 UTC, merged