added task 9.3
Frikam/SPBU_HOMEWORK pull request #29
Opened 2018-12-13 21:37 UTC by Frikam

2018-12-19 13:57 UTC, ujohnny commented on 9/9.3/9.3/main.cpp
> +            previousSign = '(';
как минимум тут можно написать `= sign` но выглядит это довольно страшно

2018-12-19 19:02 UTC, Frikam commented on 9/9.3/9.3/main.cpp
> +            previousSign = '(';
Так дело в том, что sign тут не всегда равен '(', тк я до этого ввожу sign еще раз

2018-12-23 14:11 UTC, jzuken commented
8 bytes in 1 blocks are definitely lost

2018-12-23 14:11 UTC, jzuken commented
и было бы здорово, чтобы можно было подавать выходной файл из 9.2 сюда на вход как есть

2018-12-23 14:14 UTC, jzuken requested changes

2018-12-23 14:14 UTC, jzuken commented on 9/9.3/9.3/Tree.hpp
> +void addSign(Tree *tree, List *list, char sign);
тут та же история: нужно оставить в интерфейсе только высокоуровневые операции. если хочется, можно разделить этот модуль на два: просто дерево и штуки, специфичные для хаффмана

2018-12-24 09:13 UTC, merged