added 1 task:
Frikam/SPBU_HOMEWORK pull request #35
Opened 2019-02-24 20:20 UTC by Frikam

2019-03-03 20:36 UTC, PrikhodkoStanislav requested changes

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/main.java
> +public class main {
Название класса нужно писать с заглавной буквы.

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/Stack.java
> +
Лишняя пустая строка.

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/Stack.java
> +    private class StackElement{
Нужен пробел перед фигурной скобкой.

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/Stack.java
> +    private class StackElement{
вложенные классы лучше помещать в конец объемлющих

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/Stack.java
> +
Лишняя пустая строка. Комментарий лучше прицеплять к объявлению метода без пропуска пустой строки.

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/Stack.java
> +        size+=1;
Арифметический оператор нужно обособлять пробелами.

2019-03-03 20:36 UTC, PrikhodkoStanislav commented on sem2/1/1/src/group144/tetin/main.java
> +        System.out.println("Deleted element : " + stack.pop());
Если кидаешь в pop исключения, то их нужно и ловить (try ... catch).

2019-03-04 14:46 UTC, closed without merging

2019-03-04 18:38 UTC, PrikhodkoStanislav commented
Планируешь переоткрывать pull request?

2019-03-04 18:48 UTC, Frikam commented
@PrikhodkoStanislav уже открыл новый, просто появились новые файлы и не хотел с этим возьться.