added task 2
Frikam/SPBU_HOMEWORK pull request #36
Opened 2019-02-24 20:23 UTC by Frikam

2019-03-03 20:40 UTC, PrikhodkoStanislav requested changes

2019-03-03 20:40 UTC, PrikhodkoStanislav commented on sem2/1/2/.idea/.name
> +2
Этот файл точно стоит убирать при заливке в git.

2019-03-03 20:40 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    private class Node{
Пробел перед фигурной скобкой.

2019-03-03 20:40 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    private class Node{
вложенные классы лучше помещать в конец объемлющих

2019-03-03 20:40 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        while(pointer.next != null){
Нужны пробелы вокруг выражения в скобках.

2019-03-04 16:08 UTC, PrikhodkoStanislav requested changes

2019-03-04 16:08 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    public boolean isEmpty(){
Не хватает пробелов перед фигурной скобкой.

2019-03-04 16:08 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        while(pointer.next.next != null){
Тут тоже выражение в скобках нужно выделять пробелами.
Проверяй стацлгайд! Соблюдение правил оформления поможет и тебе, и смотрящим твой код.

2019-03-08 17:54 UTC, PrikhodkoStanislav requested changes

2019-03-08 17:54 UTC, PrikhodkoStanislav commented on sem2/1/2/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл содержит внутренние настройки редактора. Его не стоит выкладывать в гит.

2019-03-08 17:54 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    List() {
Конструктор необязателен. Инициализация переменных и конструктор по-умолчанию генерируется автоматически.

2019-03-08 17:54 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        if (length == 0){
Пробел перед фигурной скобкой.

2019-03-08 17:54 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        if (length == 1){
Пробел

2019-03-08 17:54 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    public void printList(){
Поправь, пожалуйста, везде стайлгайд. Так будет и тебе проще, и читающим твой код. Далее не буду подписывать в каждой строчке, но стайлгайд нужно соблюдать во всем файле.

2019-03-08 17:57 UTC, Frikam commented on sem2/1/2/src/group144/tetin/List.java
> +    public void printList(){
@PrikhodkoStanislav Просто когда мы писали на c++, я всегда эту скобочку не на этой строке оставлял, а на строку ниже, поэтому еще не привык так. Буду стараться избегать этого

2019-03-08 18:00 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +    public void printList(){
@Frikam Да, стайлгайд C++ и Java различаются, поэтому нужно привыкать к новому стилю написания кода. Постарайся исправить и в дальнейшем придерживаться этих правил.

2019-03-10 12:06 UTC, Frikam commented on sem2/1/2/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Обновил гит игнор, теперь в других ветках этого файла не будет. Что бы он из этой ветки пропал, нужно будет ее пересоздать.

2019-03-11 19:12 UTC, jzuken requested changes

2019-03-11 19:12 UTC, jzuken commented on sem2/1/2/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
тут все ненужные файлы надо просто удалить

2019-03-11 19:12 UTC, jzuken commented on sem2/1/2/src/group144/tetin/List.java
> +public class List {
джавадок где?

2019-03-11 19:12 UTC, jzuken commented on sem2/1/2/src/group144/tetin/List.java
> +    //*add element in list*/
если это попытка сделать джавадок, то они не так оформляются

2019-03-11 19:12 UTC, jzuken commented on sem2/1/2/src/group144/tetin/List.java
> +        int value;
модификаторы видимости потерялись

2019-03-28 20:30 UTC, PrikhodkoStanislav requested changes

2019-03-28 20:30 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        Node(int value){
Пробел!

2019-03-28 20:56 UTC, PrikhodkoStanislav requested changes

2019-03-28 20:56 UTC, PrikhodkoStanislav commented on sem2/1/2/src/group144/tetin/List.java
> +        while(pointer.next.next != null) {
Пробел! Будь внимательнее!

2019-04-29 08:23 UTC, merged