added task 1
Frikam/SPBU_HOMEWORK pull request #39
Opened 2019-02-28 15:22 UTC by Frikam

2019-03-08 20:20 UTC, PrikhodkoStanislav requested changes

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/InsertionSorter.java
> +        if (length == 0){
Нет пробела перед фигурной скобкой.

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/InsertionSorter.java
> +                swap(j, j-1, array);
Нужно арифметические операции отделять пробелами.

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/BubbleSorter.java
> +                    swap(j,j + 1, array);
Пробела не хватает перед j

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/BogoSorter.java
> +    private void swap(int a, int b, int[] array){
Пробел перед фигурной скобкой.

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/BogoSorter.java
> +public class BogoSorter implements Sorter {
А ты рисковый!

2019-03-08 20:20 UTC, PrikhodkoStanislav commented on sem2/2/1/src/test/java/group144/tetin/BogoSorterTest.java
> +    public void sortReversed(){
Сколько по времени работает?

2019-03-10 11:57 UTC, Frikam commented on sem2/2/1/src/test/java/group144/tetin/BogoSorterTest.java
> +    public void sortReversed(){
Когда как, иногда 65 ms, иногда 15 ms. Ну в целом не очень долго

2019-03-11 09:39 UTC, jzuken requested changes

2019-03-11 09:39 UTC, jzuken commented on sem2/2/1/src/main/java/group144/tetin/InsertionSorter.java
> +public class InsertionSorter implements Sorter{
джавадоки где?

2019-03-28 20:32 UTC, PrikhodkoStanislav requested changes

2019-03-28 20:32 UTC, PrikhodkoStanislav commented on sem2/2/1/src/test/java/group144/tetin/InsertionSorterTest.java
> +    public void sortEmpty(){
Пробел!

2019-03-28 20:32 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/InsertionSorter.java
> +            while (j != 0 && array[j] < array[j - 1]){
Пробел! Будь внимательнее!

2019-03-28 20:32 UTC, PrikhodkoStanislav commented on sem2/2/1/src/main/java/group144/tetin/InsertionSorter.java
> +public class InsertionSorter implements Sorter{
И пробела не хватает!

2019-04-29 07:53 UTC, merged