added task 3 from homework 2
Frikam/SPBU_HOMEWORK pull request #42
Opened 2019-03-06 09:55 UTC by Frikam

2019-03-18 14:06 UTC, ujohnny commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
вот вы в обоих реализациях вызываете один и тот же метод, и ваш интерфейс печатанья имеет слово spiral. 
ведь на самом деле та сущность, которая производит output должна быть вообще spiral agnostic и должна просто превращать строчку в набор байтов либо в консоли, либо на диске.

2019-03-18 14:07 UTC, ujohnny commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
и вдобавок ко всему, получение дополнительной ф-ти через inheritance (в данном случае getPrintSpiral) это вообще неправильный способ использования наследования.

2019-03-18 14:25 UTC, ujohnny commented
в общем идея притащить градл выглядит хорошей, если ее окончательно доработать.

1. можно завернуть все домашки с один градл проект с подпроектами. 
2. если сделать шаг выше, то можно избавиться от идея конфигов и будет меньше мусора в папках, и даже не надо будет в идее каждый проект отдельно открывать.

2019-03-18 16:06 UTC, Frikam commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
@ujohnny если не через наследование, то как мне можно использовать эту функцию в двух разных классах?

2019-03-18 16:06 UTC, Frikam commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
@ujohnny не совсем понял 2 абзак вашего комментария, не могли бы вы перевразировать?

2019-03-18 20:33 UTC, ujohnny commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
а второй абзац, это какой тут? я к тому, что интерфейс вашего записывателя должен быть типа
```public void write(String text)```
а текст уже должен подаваться ему явно.

2019-03-18 20:36 UTC, ujohnny commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
ну или более детально

```
public class Formatter {
static public String formatAsSpiral(int[][] matrix);
}

public interface Writer {
public void write(String text);
}

Writer r = new ConsoleWriter();
r.write(FormatterImpl::formatAsSpiral(matrix));
```

2019-04-10 14:06 UTC, jzuken commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
а мне кажется, тут вообще не надо ничего возвращать как строку или массив байт. надо сразу при формировании спирали через полиморфизм вызывать нужный метод вывода

2019-04-17 18:52 UTC, Frikam commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
@jzuken если не возвращать строку, как в таком случае писать тесты? Я на паре вас спрашивал, вы ответили, что можно возвращать строку.

2019-04-21 12:08 UTC, jzuken commented on sem2/2/3/src/main/java/group144/tetin/OutputInConsole.java
> +        String result = getPrintSpiral(matrix);
я не про конечный результат, а про метод, который спираль обходит. он же в любом случае какой-то вывод в поток делает, в тестах поток и подменять

2019-05-17 13:43 UTC, jzuken requested changes

2019-05-17 13:43 UTC, jzuken commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
./gradlew test 
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/me/git/m18/tetin/sem2/2/3/gradle/wrapper/gradle-wrapper.properties' does not exist.
        at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)

не работает

2019-05-17 13:43 UTC, jzuken commented on sem2/2/3/src/main/java/group144/tetin/SpriralOutputter.java
> +        String answer = "";
ну, то, что я просил сделать через полиморфизм, всё ещё не сделано. и даже StringBuilder не используется

2019-05-17 14:36 UTC, Frikam commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
@jzuken с чем может быть связанна ошибка? Просто у меня работет, если прописать эту команду, да и travis не ругается

2019-05-17 14:40 UTC, jzuken commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
там же всё написано в сообщении об ошибке. тревис (да и ты походу) запускаете локально установленный градл, судя по всему

2019-05-17 14:55 UTC, Frikam commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
@jzuken как эту проблему можно исправить? 
Ниже все что содержиться в файле gradle-wrapper.properties :
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

2019-05-17 14:56 UTC, jzuken commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
ты прочитай ещё раз сообщение об ошибке. оно разве ругается на содержимое файла?

2019-05-17 14:57 UTC, jzuken commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
меня каждый раз не покидает исключение, что вы с Киреевым надо мной издеваетесь. ну или какие-то одинаковые наркотики употребляете :)

2019-05-17 15:16 UTC, Frikam commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
@jzuken Маководы \_(-_-)_/

2019-05-17 16:10 UTC, Frikam commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
@jzuken Прошу прощения, но не совсем понимаю что мне нужно сделать, что бы ошибка пропала. В файле build.gradle я что-то импортировал и не знаю, решит это проблему или нет.

2019-06-07 10:43 UTC, jzuken commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
ладно, попробуем ещё раз. что написано в сообщении об ошибке в первом моём сообщении тут?

2019-06-09 13:06 UTC, Frikam commented on sem2/2/3/gradlew
> +#!/usr/bin/env sh
@jzuken При попытке запустить тесты, у вас выдает ошибку.
Возможно ошибка была в том, что при создании тестового файла при выборе Testing libary я возможно выбрал Arqiillian JUnit 4, а не просто JUnit4

2019-06-10 14:08 UTC, closed without merging