added task 4.1
Frikam/SPBU_HOMEWORK pull request #43
Opened 2019-03-21 11:44 UTC by Frikam

2019-04-13 19:06 UTC, ujohnny commented on sem2/4/1/src/main/java/group144/tetin/List.java
> +    protected boolean ElementInList(ElementType element) {
почему protected, почему не просто exists?

2019-04-16 08:39 UTC, Frikam commented on sem2/4/1/src/main/java/group144/tetin/List.java
> +    protected boolean ElementInList(ElementType element) {
@ujohnny просто ничего не знал про exists.

2019-05-03 15:18 UTC, jzuken requested changes

2019-05-03 15:18 UTC, jzuken commented on sem2/4/1/src/main/java/group144/tetin/AlreadyInListException.java
> +public class AlreadyInListException extends Exception { }
к исключениям тоже надо писать доки

2019-05-03 15:18 UTC, jzuken commented on sem2/4/1/src/main/java/group144/tetin/UniqueList.java
> +    void add(ElementType value) throws AlreadyInListException {
ну, у этого метода другое уже поведение, это надо отразить в доках

2019-05-04 09:57 UTC, Frikam commented on sem2/4/1/src/main/java/group144/tetin/UniqueList.java
> +    void add(ElementType value) throws AlreadyInListException {
@jzuken добавление @exception и описания когда оно бросается будет достаточно?

2019-05-04 16:29 UTC, jzuken commented on sem2/4/1/src/main/java/group144/tetin/UniqueList.java
> +    void add(ElementType value) throws AlreadyInListException {
нет, нужно и в описании метода тоже отразить

2019-05-04 16:30 UTC, Frikam commented on sem2/4/1/src/main/java/group144/tetin/UniqueList.java
> +    void add(ElementType value) throws AlreadyInListException {
@jzuken отписал

2019-05-11 14:12 UTC, merged