added task 3.2
Frikam/SPBU_HOMEWORK pull request #44
Opened 2019-03-21 15:39 UTC by Frikam

2019-04-13 19:11 UTC, ujohnny commented on sem2/3/2/src/main/java/group144/tetin/OperatorNode.java
> +            left = new OperandNode(scanner.next());
у вас 2 проблемы
1. вы вызываете все конструкторы рекурсивно
2. вы смешали код, который должен парсить внутрь этих нод. что если я захочу явно создать дерево? где ожидаемый конструктор

`OperatorNode(Node left, Node right)`, который я бы вызвал как `OperatorNode(new OperandNode(1), new OperandNode(2)`

2019-04-17 18:28 UTC, Frikam commented on sem2/3/2/src/main/java/group144/tetin/OperatorNode.java
> +            left = new OperandNode(scanner.next());
@ujohnny а в чем что не так с рекурсивными конструкторами? Это же сокращяет количество кода и не особо усложняет понимание.

2019-05-03 15:20 UTC, jzuken requested changes

2019-05-03 15:20 UTC, jzuken commented on sem2/3/2/src/main/java/group144/tetin/OperatorNode.java
> +            left = new OperandNode(scanner.next());
в текущей реализации с тем, что создание дерева и создание дерева по строке -- это разные операции, которые тут неразделимы сейчас

2019-06-07 10:49 UTC, jzuken requested changes

2019-06-07 10:49 UTC, jzuken commented on sem2/3/2/src/main/java/group144/tetin/Node.java
> +public interface Node {
доки?

2019-06-07 10:49 UTC, jzuken commented on sem2/3/2/src/main/java/group144/tetin/ArithmeticTree.java
> +    ArithmeticTree(Scanner scanner){
а как мне построить дерево не по строке? ну то есть если я его захочу программно строить

2020-01-12 12:04 UTC, merged