added task 3.1
Frikam/SPBU_HOMEWORK pull request #45
Opened 2019-03-26 18:09 UTC by Frikam

2019-04-13 19:05 UTC, ujohnny requested changes

2019-04-13 19:05 UTC, ujohnny commented on sem2/3/1/src/main/java/group144/tetin/Main.java
> +            switch (command) {
строка в свитче, вы считаете это оптимальным кодом?

2019-04-13 19:05 UTC, ujohnny commented on sem2/3/1/src/main/java/group144/tetin/Main.java
> +        while (false != true) {
какое то странное условие

2019-04-13 19:05 UTC, ujohnny commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashP = hashFunction.getHash(element, hashTable.size());
если учитывать то, что при превышении лоад фактора надо таблицу перестраивать, то лучше значение используемого mod инкапсулировать внутрь алгоритма.

2019-04-13 19:05 UTC, ujohnny commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
а эти алгоритмы зачем тут и ниже перебирать?

2019-04-13 19:05 UTC, ujohnny commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +            int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
и тут тоже

2019-04-16 08:44 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
@ujohnny Дело в том, что мы во время программы мы можем несколько раз сменить хэш функцию, поэтому что бы проверить находится ли слово в таблице, нам нужно проверить не по текущей хэш функции, а по всем.

2019-04-16 08:48 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/Main.java
> +        while (false != true) {
@ujohnny тк функция возвращает тип хэш функции, я не придумал другого способа, как мне обработать возможные ошибки пользователя при выборе хэш функции (Например написать 4, а у меня такой команды нет). Из этого цикла выкинет, когда пользователь выберет хэщ функцию.

2019-04-17 18:34 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashP = hashFunction.getHash(element, hashTable.size());
@ujohnny не совсем понимаю куда нужно инкапсулировать mod, не могли бы вы перефразировать?

2019-05-04 16:33 UTC, jzuken requested changes

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/settings.gradle
> +rootProject.name = 'HashTable'
не понял, зачем тут либы выложены?

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashFunction.java
> +public interface HashFunction {
доки где?

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
вот этот момент можно поподробнее? а коллизии ты тоже по всем функциям проверять будешь?

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashP = hashFunction.getHash(element, hashTable.size());
@ujohnny, я тоже не очень понял, что ты предлагаешь. алгоритм же не знает текущий размер таблицы, и знать ему наверное не положено

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
а вот перестраивание таблицы при достижении порогов load factor сделать нужно

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/Main.java
> +        while (false != true) {
не надо так делать, никогда причём. надо немножко ещё подумать и написать нормально :)

2019-05-04 16:33 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/PolynomialHash.java
> +        int PrimeNumber = 7;
стайлгайд

2019-05-04 16:42 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
@jzuken нет, коллизии не буду по всем функциям, в этом нет необходимости, а в функции добавления элемента необходимо, тк не может быть такого, что в нашей таблицы одинаковые элементы с разными хэшами лежат.

2019-05-04 17:44 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
я ничего не понял. почему нет необходимости в коллизиях? почему не может быть такого?

2019-05-05 13:29 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashM = new SymbolsMultiplicationHash().getHash(element, hashTable.size());
@jzuken тк я давно писал код уже подзабыл что там происходило, действительно нужно добавить проверку на то, что слово уже находится в таблице

2019-05-17 11:17 UTC, jzuken requested changes

2019-05-17 11:17 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        this.hashFunction = hashFunction;
а вот теперь посмотри на эту строчку и подумай, как дальше эта таблица работать будет

2019-05-17 11:17 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +                add(hashTable.get(i).pop());
не понял, это как работает? add() же с тем же самым полем hashTable работает

2019-05-17 11:17 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashD = new SquaredLengthHash().getHash(element, hashTable.size());
а эта дичь тут всё ещё нужна?

2019-05-17 11:17 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        for (LinkedList list : hashTable) {
параметр генерика потерялся

2019-05-17 16:27 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/Main.java
> +        while (false != true) {
@jzuken есть ли смысл создать переменную, которая равна true и выполнять, пока эта переменная true? Думаю будет лучше, чем раньше, тк название переменной будет передавать причину, по которой мы так делаем

2019-05-17 16:27 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +                add(hashTable.get(i).pop());
@jzuken не совсем, у меня хэш функция зависит от размера hashTable, соответственно тут я увеличил размер таблицы, следовательно хэш функция будет считаться по другому

2019-05-17 16:28 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        this.hashFunction = hashFunction;
@jzuken нужно было при смене хэш функции для каждого элемента хэш таблицы пересчитывать хэш функцию?

2019-05-17 16:41 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        int hashD = new SquaredLengthHash().getHash(element, hashTable.size());
@jzuken если при изменении хэш функции, не перестраивать хэш таблицу, то да, это все еще нужно

2019-06-07 10:47 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        for (int i = 0; i < numberOfNewСell; i++) {
эм, а если таблица уменьшается?

2019-06-07 10:47 UTC, jzuken commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +                add(hashTable.get(i).pop());
ну функция то да, но как ты будешь итерироваться по таблице, если ты добавляешь в неё же? да и этот цикл никогда не закончится, на каждой итерации ты берёшь элемент и сразу же кладёшь его обратно, размер меньше не становится. или я что не понимаю?

2019-06-07 13:04 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +                add(hashTable.get(i).pop());
@jzuken действительно, не подумал о том, что элемент попадет в эту же ячейку

2019-06-07 14:42 UTC, Frikam commented on sem2/3/1/src/main/java/group144/tetin/HashTable.java
> +        for (int i = 0; i < numberOfNewСell; i++) {
@jzuken таблица не может уменьшится, у нас таблица перестраивается при смене хэш функции и при достижении порога load factor'a

2019-06-13 11:21 UTC, merged