2.5.2
Frikam/SPBU_HOMEWORK pull request #49
Opened 2019-04-02 13:04 UTC by Frikam

2019-05-04 17:30 UTC, jzuken commented
та же история с зумом

2019-05-04 17:31 UTC, jzuken requested changes

2019-05-04 17:31 UTC, jzuken commented on sem2/5/2/src/main/java/group144/tetin/Controller.java
> +    private void calculate() {
вот в такой реализации часть с логикой приложения (подсчёт выражения) неотделима от части обработки UI. её же отдельно не протестировать даже никак. надо разделить их на две сущности

2019-06-07 10:54 UTC, jzuken commented
моё замечание про разделение осталось без внимания :(

2019-06-07 10:57 UTC, Frikam commented on sem2/5/2/src/main/java/group144/tetin/Controller.java
> +    private void calculate() {
@jzuken будет номармально, если я буду передавать переменные при вызове функции?
Тогда firstNumber.value() будет замененно на firstNumber

2019-06-11 09:52 UTC, jzuken commented
ну и зачем мы делали это разделение? правильно, чтобы протестировать логику

2019-06-11 09:53 UTC, jzuken commented
ну и зачем мы делали это разделение? правильно, чтобы протестировать логику

2019-06-13 11:21 UTC, merged