added task 5.3
Frikam/SPBU_HOMEWORK pull request #50
Opened 2019-04-07 16:21 UTC by Frikam

2019-05-04 17:49 UTC, jzuken commented
ну стандартный калькулятор не так работает, он не ждёт, пока ты всё выражение введёшь, а считает его сразу

2019-05-04 17:50 UTC, jzuken commented
и то же замечание про зум здесь

2019-05-04 17:51 UTC, jzuken requested changes

2019-05-04 17:51 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Contoller.java
> +                expression+= "" + i;
StringBuilder

2019-05-04 17:51 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +    String postfixForm;
модификатор

2019-05-04 17:51 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +                catch (Exception e) {
и в чём смысл этого?

2019-06-07 10:58 UTC, jzuken commented
ну ок, я подожду, пока все замечания поправятся.
и ещё, кстати, оно не даёт вводить второй аргумент из нескольких цифр

2019-06-07 11:00 UTC, Frikam commented
@jzuken Прошу прощения, забыл это исправить) Обратил свое внимание только на зум просто

2019-06-11 09:57 UTC, jzuken requested changes

2019-06-11 09:57 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +                    throw e;
и в чём смысл этого телодвижения тут?

2019-06-11 09:57 UTC, jzuken commented on sem2/5/3/src/test/java/group144/tetin/CalculatorTest.java
> +public class CalculatorTest {
тестов явно маловато. например, нет теста на две операции подряд

2019-06-11 13:05 UTC, Frikam commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +                    throw e;
@jzuken Сейчас добавил еще одно исключение, Арифметическая ошибка на тот случай, если делим на 0, и Exception если выражение введенно неверено

2019-06-13 11:27 UTC, jzuken requested changes

2019-06-13 11:27 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +            if (expression.equals("")) {
isEmpty() чем не угодил?

2019-06-13 11:27 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +                    throw e;
эээ. мой вопрос был, в чём смысл ловить исключение, чтобы потом просто бросить его дальше? было бы ровно такое же поведение, если бы ты вообще ничего не написал. это какой-то антипаттерн: ты написал какой-то код и не сделал вообще ничего полезного

2019-06-13 20:36 UTC, Frikam commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +            if (expression.equals("")) {
@jzuken не знал что есть эта функция

2019-09-27 07:49 UTC, jzuken requested changes

2019-09-27 07:49 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +            postfixForm += " " + stackSign.pop();
строки неизменяемые, так что лучше пользоваться StringBuilder. и тут несколько мест таких

2019-09-27 07:49 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Calculator.java
> +    public int priorityOfSign(char sign) {
кажется, что это за пределами калькулятора никому не надо

2019-09-27 07:49 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Main.java
> +public class Main extends Application {
и ещё хочется, чтобы оно считало выражение сразу, не дожидаясь, пока нажмут знак равно. как стандартные калькуляторы

2019-09-27 10:51 UTC, Frikam commented on sem2/5/3/src/main/java/group144/tetin/Main.java
> +public class Main extends Application {
@jzuken У меня оно так и делает, но считает после нажатия на операцию, если бы оно считало сразу, то нельзя было бы вводить двухзначные и более числа

2019-09-27 12:28 UTC, jzuken commented on sem2/5/3/src/main/java/group144/tetin/Main.java
> +public class Main extends Application {
и как тогда я сделал такое?

<img width="387" alt="Screenshot 2019-09-27 at 16 27 48" src="https://user-images.githubusercontent.com/705678/65769110-d854b800-e143-11e9-8de5-e6feaee98169.png">

2019-09-28 20:44 UTC, Frikam commented on sem2/5/3/src/main/java/group144/tetin/Main.java
> +public class Main extends Application {
@jzuken Я тут намудрил просто, я вместо того что бы сделать отдельную кнопку для смены знака у числа, пытался сделать так, что бы знак у числа можно было бы менять с помощью обычного минуса.

2019-09-28 21:25 UTC, Frikam commented
@jzuken Тут получилось так, что в коде контроллера очень много кода, который связан с логикой и получается интерфейс от логики не совсем отделен, или все же такая обработка случаев допустима в коде интерфейса?

2019-09-28 21:37 UTC, Frikam commented
@jzuken hwproj не позволяет залить эту ссылку в задачу

2020-01-12 12:04 UTC, merged