added task 6.2
Frikam/SPBU_HOMEWORK pull request #51
Opened 2019-04-09 15:10 UTC by Frikam

2019-05-05 12:32 UTC, jzuken requested changes

2019-05-05 12:32 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTakToe.java
> +            if (!buttons[i][0].getText().equals("") && buttons[i][0].getText() == buttons[i][1].getText() && buttons[i][1].getText() == buttons[i][2].getText()) {
строки нельзя через == на равенство сравнивать

2019-05-05 12:32 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTakToe.java
> +        for (int i = 0; i < 3; i++) {
а можно это как-то к размеру доски привязать?

2019-05-05 12:32 UTC, jzuken commented on sem2/6/2/src/main/resources/group144/tetin/GUI.fxml
> +<AnchorPane prefHeight="250.0" prefWidth="300.0" style="-fx-background-color: DARKGREY;" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="group144.tetin.Cont
тут тоже хочется зум окна

2019-05-05 12:32 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/Controller.java
> +        if ("X".equals(textOnButton)) {
здесь та же история с разделением логики и графики. на правила игры вообще надо тесты написать бы

2019-06-07 11:02 UTC, jzuken requested changes

2019-06-07 11:02 UTC, jzuken commented on sem2/6/2/src/test/java/group144/tetin/TicTakToeTest.java
> +    public void isAnybodyWinTest10() {
это очень, очень плохие имена тестов

2019-06-07 11:02 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTakToe.java
> +public class TicTakToe {
TicTacToe

2019-06-07 11:02 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/Controller.java
> +        textOnButtons = new String[3][3];
:(

2019-06-07 11:02 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTakToe.java
> +            if (result == true) {
зачем сравнивать с true?

2019-06-07 11:02 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTakToe.java
> +        boolean result;
крайне неудачное имя

2019-06-07 12:40 UTC, Frikam commented on sem2/6/2/src/main/java/group144/tetin/Controller.java
> +        textOnButtons = new String[3][3];
@jzuken Нужно создать переменную для тройки или проблема с стайлгайдом?

2019-06-07 12:52 UTC, Frikam commented on sem2/6/2/src/main/java/group144/tetin/Controller.java
> +        textOnButtons = new String[3][3];
@jzuken или не инициализировать тут не нужно инициализировать массив

2019-06-11 09:59 UTC, jzuken requested changes

2019-06-11 09:59 UTC, jzuken commented on sem2/6/2/src/main/java/group144/tetin/TicTacToe.java
> +        }
эпик вин

2019-06-13 11:27 UTC, merged