added task 7.2
Frikam/SPBU_HOMEWORK pull request #57
Opened 2019-05-31 12:21 UTC by Frikam

2019-06-11 10:05 UTC, jzuken requested changes

2019-06-11 10:05 UTC, jzuken commented on sem2/7/2/src/test/java/group144/tetin/ReflectorTest.java
> +        assertEquals(excepted, reflector.printStructure(printedClass));
> Task :test FAILED

group144.tetin.ReflectorTest > printStructureWithExceptionsTest FAILED
    org.junit.ComparisonFailure at ReflectorTest.java:52

4 tests completed, 1 failed

2019-06-11 10:05 UTC, jzuken commented on sem2/7/2/src/test/java/group144/tetin/ReflectorTest.java
> +        assertEquals(excepted, reflector.printStructure(printedClass));
![2019-06-11 13_03_10-Comparison Failure](https://user-images.githubusercontent.com/705678/59263216-4a62c900-8c49-11e9-8a8a-42a619b1fd26.png)

2019-06-11 10:05 UTC, jzuken commented on sem2/7/2/src/main/java/group144/tetin/Reflector.java
> +        FileWriter fileWriter = new FileWriter( "src//test//java//group144//tetin//ResultOfReflection//" + someClass.getSimpleName() + ".java");
длинновата строка

2019-06-11 10:05 UTC, jzuken commented on sem2/7/2/src/main/java/group144/tetin/Reflector.java
> +        newClass.append("package " + someClass.getPackage().getName() + ".ResultOfReflection;" + "\n\n" );
![2019-06-11 13_03_52-2  C__Users_jetbrains_git_m18_tetin_sem2_7_2  -  _src_main_java_group144_tetin](https://user-images.githubusercontent.com/705678/59263268-623a4d00-8c49-11e9-868a-16edc813ef0e.png)

2019-06-11 10:55 UTC, Frikam commented on sem2/7/2/src/test/java/group144/tetin/ReflectorTest.java
> +        assertEquals(excepted, reflector.printStructure(printedClass));
@jzuken честно говоря не знаю почему у вас выводит так, я запустил printStructure для этого класса, и результат был который и ожидался

2019-06-13 11:30 UTC, jzuken requested changes

2019-06-13 11:30 UTC, jzuken commented on sem2/7/2/src/main/java/group144/tetin/Reflector.java
> +            newClass.append("\t" + someClass.getSimpleName() + " ");
ну вообще предполагалось, что ты везде это поправишь

2019-09-27 07:52 UTC, merged