added task 9.1
Frikam/SPBU_HOMEWORK pull request #59
Opened 2019-06-06 11:56 UTC by Frikam

2019-06-11 09:03 UTC, Frikam commented
How to start a game : 
1. Launch RunServer
2. Launch RunClient

2019-06-13 11:41 UTC, jzuken requested changes

2019-06-13 11:41 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Controller.java
> +        if (game.state() != "PLAYING") {
это объекты вроде как

2019-06-13 11:41 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Encoder.java
> +                byteBuffer.put((byte) 1);
копипаста

2019-06-13 11:41 UTC, jzuken commented on sem2/9/1/build.gradle
> +plugins {
➜ ./gradlew test
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/Users/timofey.bryksin/git/spbu-18/tetin/sem2/9/1/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)

2019-06-13 21:19 UTC, Frikam commented on sem2/9/1/build.gradle
> +plugins {
@jzuken тк этот файл был раньше в гитигноре, поэтому пересоздам ветку с нормальным гитигнор файлом

2019-06-13 21:20 UTC, closed without merging