Пересоздал ветку с нормальным гитигнор файлом
Frikam/SPBU_HOMEWORK pull request #61
Opened 2019-06-13 21:24 UTC by Frikam

2019-09-27 08:10 UTC, jzuken requested changes

2019-09-27 08:10 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Game.java
> +        if (result) {
классика

2019-09-27 08:10 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Controller.java
> +    String me;
этим товарищам области видимости правильной не хватает

2019-09-27 08:10 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Controller.java
> +    Button button_0_0;
и этим тоже. ну и лучше все поля вместе группировать

2019-09-27 08:10 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/ControllerClient.java
> +                return;
а это последний оператор в этом методе, return тут бесполезен. и там ещё несколько мест таких есть

2019-09-27 08:10 UTC, jzuken commented on sem2/9/1/src/main/java/group144/tetin/Game.java
> +                    result = false;
а тут вполне можно сделать break

2019-09-28 21:42 UTC, Frikam commented on sem2/9/1/src/main/java/group144/tetin/Controller.java
> +    Button button_0_0;
@jzuken а есть ли в этом необходимость? Просто я думал, что можно оставить на верху те поля, которые будут полезны в коде, а если эти поля перенести наверх, то они просто будут заполнять место и они как таковой роли не играют в методах.
Я просто пытаюсь понять как будет лучше.

2020-01-12 12:04 UTC, merged