add tasks without java docs
Frikam/SPBU_HOMEWORK pull request #66
Opened 2019-11-05 20:07 UTC by Frikam

2019-12-08 12:51 UTC, jzuken commented
хотелось, чтобы влево тоже можно было бы стрелять. и чтобы пульки не пролетали сквозь землю

2019-12-08 13:06 UTC, jzuken requested changes

2019-12-08 13:06 UTC, jzuken commented on sem3/3/1/src/main/java/Ground.java
> +    public static int coordinatesCannonAfterMovingRight(int x) {
это какой-то очень странный ОО-дизайн

2019-12-08 13:06 UTC, jzuken commented on sem3/3/1/src/main/java/Ground.java
> +        if (x > 0) {
а тут не надо проверять, что оно за границу вылезло?

2019-12-08 13:06 UTC, jzuken commented on sem3/3/1/src/main/java/Mountains.java
> +public class Mountains {
а чего оно с Ground никак не связано?

2019-12-08 13:06 UTC, jzuken commented on sem3/3/1/src/main/java/Bullet.java
> +    private boolean isFly = false;
является ли оно мухой? оригинально

2019-12-08 13:06 UTC, jzuken commented on sem3/3/1/src/main/java/Bullet.java
> +            e.printStackTrace();
:(

2019-12-08 19:05 UTC, Frikam commented on sem3/3/1/src/main/java/Ground.java
> +        if (x > 0) {
@jzuken так это она и есть, x - это координата начала пушки

2019-12-09 16:07 UTC, Frikam commented on sem3/3/1/src/main/java/Ground.java
> +    public static int coordinatesCannonAfterMovingRight(int x) {
@jzuken я возможно не совсем правильно понял ваши слова, я думал, что класс пушка не должен отвечать за логику движения, он не должен проверять выходит ли он за рамки окна или нет, так же не нужно ему проверять заехала ли пушка на гору, поэтому вынес эту логику в отдельный класс.

2019-12-10 04:35 UTC, jzuken commented on sem3/3/1/src/main/java/Ground.java
> +    public static int coordinatesCannonAfterMovingRight(int x) {
концепутально всё верно, но почему тут статические методы?

2019-12-10 10:44 UTC, Frikam commented on sem3/3/1/src/main/java/Ground.java
> +    public static int coordinatesCannonAfterMovingRight(int x) {
@jzuken my bad

2019-12-24 11:10 UTC, jzuken commented
ну теперь оно не стреляет, когда стоит на горе :)

2019-12-24 11:12 UTC, jzuken requested changes

2019-12-24 11:12 UTC, jzuken commented on sem3/3/1/src/main/java/GameController.java
> +    Cannon cannon;
а этот что без видимости?

2019-12-25 08:48 UTC, merged