added 5.5
Frikam/SPBU_HOMEWORK pull request #9
Opened 2018-11-08 11:05 UTC by Frikam

2018-11-20 08:17 UTC, jzuken requested changes

2018-11-20 08:17 UTC, jzuken commented on 5/5.5/5.5/main.cpp
> +            if (line[i] == '('){
это логика калькулятора

2018-11-20 09:12 UTC, Frikam commented on 5/5.5/5.5/main.cpp
> +            if (line[i] == '('){
Если я создам функцию, которая будет выполнять эту часть кода, и перемещю ее в файл калькулятор. Будет нормально?

2018-11-20 09:18 UTC, jzuken commented on 5/5.5/5.5/main.cpp
> +            if (line[i] == '('){
да

2018-11-24 17:49 UTC, jzuken requested changes

2018-11-24 17:49 UTC, jzuken commented on 5/5.5/5.5/Calculator.cpp
> +            deleteUntilOpenedBracket(stackSign, postfixForm, &*index);
а можно по ссылке аргументы передавать, чтобы не было двойных указателей?

2018-11-24 17:49 UTC, jzuken commented on 5/5.5/5.5/Calculator.hpp
> +void calculator(List *list, int firstNumber, int secondNumber, char sign);
имя функции -- глагол. десять раз уже говорил, наверное

2018-11-24 17:49 UTC, jzuken commented on 5/5.5/5.5/Calculator.hpp
> +int priorityOfSign(char sign);
а точно эти функции все нужны в открытом интерфейсе модуля калькулятора?

2018-11-24 17:49 UTC, jzuken commented on 5/5.5/5.5/FromInfixToPostfix.hpp
> +void stackPop(List *list);
от этой строчки случается когнитивный диссонанс. у тебя стек или список в итоге?

2018-12-04 12:19 UTC, jzuken requested changes

2018-12-04 12:19 UTC, jzuken commented on 5/5.5/5.5/main.cpp
> +#include "FromInfixToPostFix.hpp"
там файл не так немного называется. ты ж маковод вроде, у тебя оно тоже компилироваться не должно

2018-12-04 12:19 UTC, jzuken commented on 5/5.5/5.5/FromInfixToPostfix.cpp
> +void addElementInStacAndInArray(Stack *stackSign, char *line, char *postfixForm, int i, int &index)
плохое имя, слишком длинное и подробное

2018-12-04 12:19 UTC, jzuken commented on 5/5.5/5.5/main.cpp
> +        addElementInStacAndInArray(stackSign, line, postfixForm, i, index);
это всё детали реализации. что клиент хочет, так это посчитать выражение, то есть вызвать метод calculate(), а всё остальное его мало интересует

2018-12-19 11:27 UTC, jzuken commented
оно все еще не компилируется

2018-12-19 11:28 UTC, jzuken requested changes

2018-12-19 11:28 UTC, jzuken commented on 5/5.5/5.5/main.cpp
> +    Stack *stackSign = createList();
нафига главной программе знать про стек?

2018-12-21 14:35 UTC, merged